library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(googleVis)

shinyUI(dashboardPage(
  dashboardHeader(title ='OKCupid Profiles'),
  
  dashboardSidebar(
    sidebarUserPanel('Sean Kickham',
                     image = 'https://yt3.ggpht.com/-04uuTMHfDz4/AAAAAAAAAAI/AAAAAAAAAAA/Kjeupp-eNNg/s900-c-k-no-mo-rj-c0xffffff/photo.jpg'),
    sidebarMenu(
      menuItem('Overview', tabName = 'overview', icon = icon('eye')),
      menuItem('Findings', 
               menuSubItem('The "Average" User', 
                           tabName = 'averagefindings', 
                           icon = icon('user-circle-o')),
               menuSubItem('Gender Findings', 
                           tabName = 'genderfindings', 
                           icon = icon('female')),
               menuSubItem('Age Findings', 
                           tabName = 'agefindings', 
                           icon = icon('drivers-license-o')),
               menuSubItem('Orientation Findings', 
                           tabName = 'orientationfindings', 
                           icon = icon('compass')),
               menuSubItem('Essay Analysis', 
                           tabName = 'essayfindings',
                           icon = icon('pencil')),
               menuSubItem('Conclusions and Questions', 
                           tabName = 'conclusions', 
                           icon = icon('question')),
               icon = icon('bar-chart')),
      menuItem('Gender', tabName = 'sex', icon = icon('venus-mars')),
      menuItem('Sexual Orientation', tabName = 'orientation', icon = icon('heart')),
      menuItem('Ethnicity', tabName = 'ethnicity', icon = icon('globe')),
      menuItem('Religion', tabName = 'religion', icon = icon('star-o')),
      menuItem('Age', tabName = 'age', icon = icon('group')),
      menuItem('Data', tabName = 'data', icon = icon('database'))),
    
    selectizeInput('selected',
                   'Select Item to Display',
                   choice)
    ),
  
  
  dashboardBody(
    tags$head(tags$script(src = 'scroll.js')),
    tags$head(tags$link(rel = "stylesheet", type = "text/css", href = 'scroll.css')),
    tabItems(
      tabItem(tabName = 'overview',
              h1('Data Overview'),
              fluidRow(column(1, ''),column(6, textOutput('overviewtext'))),
              br(),
              fluidRow(column(1, ''), column(6, uiOutput('overviewvideo'))),
              br(),
              fluidRow(column(1, ''),column(6, textOutput('overviewtext2')))),
      
      tabItem(tabName = 'averagefindings',
              fluidRow(column(1, ''),
                       column(6, imageOutput('average')),
                       column(4, textOutput('averagetext'))),
              br(), br(), br(), br(),
              br(), br(), br(), br(),
              fluidRow(column(1, ''),
                       column(3, selectizeInput('groupbyCat',
                                      'Feature Category',
                                      choices = colnames(p3),
                                      width = 200)),
                       column(3, selectizeInput('groupbyCat2',
                                      'Second Category',
                                      choices = colnames(p3),
                                      width = 200))),
              fluidRow(DT::dataTableOutput('groupbytable'),
                       width = '100%')
              ),
      
      tabItem(tabName = 'genderfindings',
              fluidRow(column(6, imageOutput('genderimage')),
                       column(6, imageOutput('genderimage2'))),
              fluidRow(textOutput('gendertext'))),
      
      tabItem(tabName = 'agefindings',
              fluidRow(column(6, imageOutput('ageimage')),
                       column(6, imageOutput('ageimage2'))),
              fluidRow(textOutput('agetext'))),
      
      tabItem(tabName = 'orientationfindings',
              fluidRow(column(6, imageOutput('orientationimage')),
                       column(6, imageOutput('orientationimage2'))),
              fluidRow(textOutput('orientationtext'))),

      tabItem(tabName = 'essayfindings',
              fluidRow(column(6, imageOutput('menWC')),
                       column(6, imageOutput('womenWC'))),
              fluidRow(textOutput('wctext1')),
              fluidRow(column(6, imageOutput('christianWC')),
                       column(6, imageOutput('atheistWC'))),
              fluidRow(textOutput('wctext2'))),
      
      tabItem(tabName = 'conclusions',
              fluidRow(textOutput('conclusiontext')),
              br(), br(), br(), br(), br(),
              fluidRow(textOutput('questiontext'))),
      
      tabItem(tabName = 'sex',
              fluidRow(infoBoxOutput('femaleBox'),
                       infoBoxOutput('maleBox'),
                       infoBoxOutput('sexBox')),
              fluidRow(box(plotOutput('sexBar'),
                           height = 400),
                       box(plotOutput('sexBoxPlot'),
                           height = 400)),
              fluidRow(column(3, selectizeInput('sexAgainst',
                                                'Fill Category',
                                                choices = c('Education', 'Status', 'Orientation', 'Ethnicity',
                                                            'Religion', 'Body.Type', 
                                                            'Job', 'Offspring', 'Smokes', 'Drinks',
                                                            'Drugs', 'Diet', 'Cats', 'Dogs'),
                                                width = 200)),
                       column(3, radioButtons('sexPosition',
                                              'Graph Positions',
                                              choices = c('fill', 'dodge'),
                                              width = 100)),
                       
                       column(3, selectizeInput('sexBoxPlotCat',
                                                'Y Axis',
                                                choices = c('Income', 'Age', 'Height', 
                                                            'Religion.Serious', 'Sign.Serious'),
                                                width = 200)),
                       column(3, radioButtons('sexBoxPlotTrans',
                                              'Y Scale',
                                              choices = c('log10', 'identity'),
                                              width = 100))
              )),
      
      
      tabItem(tabName = 'orientation',
              fluidRow(infoBoxOutput('straightBox'),
                       infoBoxOutput('gayBox'),
                       infoBoxOutput('bisexualBox')),
              fluidRow(box(plotOutput('orientationBar'),
                           height = 400),
                       box(plotOutput('orientationBoxPlot'),
                           height = 400)),
              fluidRow(column(3, selectizeInput('orientationAgainst',
                                      'Fill Category',
                                      choices = c('Gender', 'Status', 'Ethnicity',
                                                  'Religion', 'Body.Type', 'Education',
                                                  'Job', 'Offspring', 'Smokes', 'Drinks',
                                                  'Drugs', 'Diet', 'Cats', 'Dogs'),
                                      width = 200)),
                       column(3, radioButtons('orientationPosition',
                                              'Graph Positions',
                                              choices = c('fill', 'dodge'),
                                              width = 100)),
                       
                       column(3, selectizeInput('orientationBoxPlotCat',
                                      'Y Axis',
                                      choices = c('Income', 'Age',  'Height', 
                                                  'Religion.Serious', 'Sign.Serious'),
                                      width = 200)),
                       column(3, radioButtons('orientationBoxPlotTrans',
                                              'Y Scale',
                                              choices = c('log10', 'identity'),
                                              width = 100))
                       )),
      
      
      tabItem(tabName = 'ethnicity',
              fluidRow(infoBoxOutput('whiteBox'),
                       infoBoxOutput('multiethnicBox'),
                       infoBoxOutput('otherBox')),
              fluidRow(box(plotOutput('ethnicityBar'),
                           height = 400),
                       box(plotOutput('ethnicityBoxPlot'),
                           height = 400)),
              fluidRow(column(3, selectizeInput('ethnicityAgainst',
                                                'Fill Category',
                                                choices = c('Smokes','Gender', 'Orientation', 'Status',
                                                            'Religion', 'Body.Type', 'Education',
                                                            'Job', 'Offspring',  'Drinks',
                                                            'Drugs', 'Diet', 'Cats', 'Dogs'),
                                                width = 200)),
                       column(3, radioButtons('ethnicityPosition',
                                              'Graph Positions',
                                              choices = c('fill', 'dodge'),
                                              width = 100)),
                       
                       column(3, selectizeInput('ethnicityBoxPlotCat',
                                                'Y Axis',
                                                choices = c('Income','Age',  'Height', 
                                                            'Religion.Serious', 'Sign.Serious'),
                                                width = 200)),
                       column(3, radioButtons('ethnicityBoxPlotTrans',
                                              'Y Scale',
                                              choices = c('log10', 'identity'),
                                              width = 100))
              )),
      
      
      tabItem(tabName = 'religion',
              fluidRow(infoBoxOutput('religiousBox'),
                       infoBoxOutput('relseriousBox'),
                       infoBoxOutput('christianBox')),
              fluidRow(box(plotOutput('religionBar'),
                           height = 400),
                       box(plotOutput('religionBoxPlot'),
                           height = 400)),
              fluidRow(column(3, selectizeInput('religionAgainst',
                                                'Fill Category',
                                                choices = c('Education', 'Gender', 'Orientation', 'Status', 
                                                            'Ethnicity', 'Body.Type', 
                                                            'Job', 'Offspring', 'Smokes', 'Drinks',
                                                            'Drugs', 'Diet', 'Cats', 'Dogs'),
                                                width = 200)),
                       column(3, radioButtons('religionPosition',
                                              'Graph Positions',
                                              choices = c('fill', 'dodge'),
                                              width = 100)),
                       
                       column(3, selectizeInput('religionBoxPlotCat',
                                                'Y Axis',
                                                choices = c('Income', 'Age',  'Height', 
                                                            'Religion.Serious', 'Sign.Serious'),
                                                width = 200)),
                       column(3, radioButtons('religionBoxPlotTrans',
                                              'Y Scale',
                                              choices = c( 'log10', 'identity'),
                                              width = 100))
              )),
      
      
      tabItem(tabName = 'age',
              fluidRow(infoBoxOutput('ageBox1'),
                       infoBoxOutput('ageBox2'),
                       infoBoxOutput('ageBox3')),
              fluidRow(box(plotOutput('ageHist'),
                           height = 400),
                       box(plotOutput('ageScatter'),
                           height = 400)),
              fluidRow(column(3, selectizeInput('ageAgainst',
                                                'Fill Category',
                                                choices = c('Drinks', 'Gender', 'Orientation', 'Status', 
                                                            'Ethnicity', 'Religion', 'Body.Type', 'Education',
                                                            'Job', 'Offspring', 'Smokes', 
                                                            'Drugs', 'Diet', 'Cats', 'Dogs'),
                                                width = 200)),
                       column(3, radioButtons('agePosition',
                                              'Graph Positions',
                                              choices = c('fill', 'dodge'),
                                              width = 100)),
                       
                       column(2, selectizeInput('ageScatter',
                                                'Y Axis',
                                                choices = c( 'Height', 'Income',
                                                            'Religion.Serious', 'Sign.Serious'),
                                                width = 200)),
                       column(2, radioButtons('ageScatterTrans',
                                              'Y Scale',
                                              choices = c('identity', 'log10'),
                                              width = 100)),
                       column(2, selectizeInput('ageScatterColor',
                                                'Fill Category',
                                                choices = c('Gender', 'Orientation', 'Status', 
                                                            'Ethnicity', 'Religion', 'Body.Type', 'Education',
                                                            'Job', 'Offspring', 'Smokes', 'Drinks',
                                                            'Drugs', 'Diet', 'Cats', 'Dogs'),
                                                width = 200))
                       )),
      
      
      tabItem(tabName = 'data',
              fluidRow(DT::dataTableOutput('table'),
                           width = '100%'))
      )
    )
  
  ))

