# -*- coding: utf-8 -*-
import scrapy
from scrapy import Spider
from scrapy.selector import Selector
from gcor.items import GcorItem
from time import sleep
import numpy as np

class GcorSpider(Spider):
	name = 'googlecorrelate'
	allowed_urls = ['https://trends.google.com/trends/']
	start_urls = ['https://www.google.com/trends/correlate']

	def verify(self, content):
		if isinstance(content, list):
			if len(content) > 0:
				content = content[0]    # convert unicode to str
				return content.encode('ascii','ignore')
			else:
				return ""
		else:                           # convert unicode to str
			return content.encode('ascii','ignore')
	# >>>>>>>>> It is better if you could save the list in a local file and load it in the parse function. <<<<<<<<<
	def parse(self, response):
		search_list=[
		"2U",
		"A+V+Homes",
		"A10+Networks",
		"Accenture",
		"ACI+Worldwide",
		"Activision+Blizzard",
		"Actua+Corporation",
		"Acushnet",
		"Adobe",
		"Aflac",
		"Agilysys",
		"Akamai+Technologies",
		"Alarm.com",
		"Alleghany+Corporation",
		"Alliance+Data+Systems",
		"Allied+World+Assurance",
		"Allscripts+Healthcare+Solutions",
		"Allstate",
		"Google",
		"Alteryx",
		"Amber+Road",
		"Amdocs+Limited",
		"American+Equity+Investment+Life",
		"American+Financial",
		"American+National+Insurance",
		"American+Software",
		"AMERISAFE",
		"AmTrust+Financial",
		"Angie's+List",
		"ANSYS",
		"AppFolio",
		"Apptio",
		"Arch+Capital+Group+Ltd.",
		"Argo+Group",
		"Aspen+Insurance",
		"Aspen+Technology",
		"athenahealth",
		"Atlas+Financial",
		"Atlassian+Corp",
		"Autodesk",
		"Automatic+Data+Processing",
		"Baldwin+&+Lyons",
		"Barracuda+Networks",
		"Bassett+Furniture",
		"Bazaarvoice",
		"Beazer+Homes",
		"Benefitfocus",
		"Black+Diamond",
		"Black+Knight+Financial",
		"Blackbaud",
		"BlackLine",
		"Blucora",
		"Blue+Capital+Reinsurance",
		"Boingo+Wireless",
		"Bottomline+Technologies",
		"Box",
		"Briggs+&+Stratton",
		"Brightcove",
		"Broadridge+Financial+Solutions",
		"BroadSoft",
		"Brunswick+Corporation",
		"CA",
		"CACI+International",
		"CalAtlantic",
		"Caleres",
		"Callaway+Golf",
		"Callidus+Software",
		"Carbonite",
		"Cass+Information+Systems",
		"Castlight+Health",
		"Cavco+Industries",
		"CDW",
		"Century+Communities",
		"Cerner",
		"Channeladvisor",
		"Check+Point+Software+Technologies",
		"China+Customer+Relations+Centers",
		"Chubb+Limited",
		"Cincinnati+Financial",
		"Citizens",
		"Citrix+Systems",
		"Cloudera",
		"CNO+Financial",
		"Cognizant+Technology",
		"Columbia+Sportswear",
		"CommerceHub",
		"CommVault",
		"Computer+Programs+and+Systems",
		"Computer+Services",
		"Convergys",
		"Cooper+Tire",
		"CoreLogic",
		"Cornerstone+Ondemand",
		"CoStar+Group",
		"Coupa+Software",
		"CPI+Card",
		"Crocs",
		"CSG+Systems",
		"CSRA",
		"CyberArk",
		"D.R.+Horton",
		"Deckers+Outdoor",
		"DHI+Group",
		"Digimarc",
		"Donegal+Group",
		"Dorman+Products",
		"DST+Systems",
		"Duluth+Holdings",
		"DXC+Technology",
		"eHealth",
		"Electronic+Arts",
		"Elio+Motors",
		"Ellie+Mae",
		"EMC+Insurance",
		"Employers+Holdings",
		"Endurance+International",
		"EnerNOC",
		"EPAM+Systems",
		"Erie+Indemnity",
		"Escalade",
		"Ethan+Allen",
		"Euronet+Worldwide",
		"Everbridge",
		"Everest+Re",
		"EVERTEC",
		"Exa+Corporation",
		"ExlService",
		"Facebook",
		"Fair+Isaac",
		"FBL+Financial",
		"Federated+National",
		"Fidelity+&+Guaranty+Life",
		"Fidelity+National+Information+Services",
		"FireEye",
		"First+Data",
		"Fiserv",
		"Fitbit",
		"Five9",
		"Flexsteel",
		"Ford",
		"Fossil+Group",
		"Fox+Factory",
		"G-III+Apparel",
		"General+Motors",
		"Genworth+Financial",
		"Gigamon",
		"Global+Indemnity",
		"Global+Payments",
		"Globant",
		"Glu+Mobile",
		"GoDaddy",
		"Goodyear+Tire",
		"GoPro",
		"Green+Brick+Partners",
		"Greenlight+Capital+Re",
		"GrubHub",
		"Guess",
		"Guidance+Software",
		"Guidewire",
		"Hallmark+Financial",
		"Hanesbrands",
		"Hanover+Insurance",
		"Harley-Davidson",
		"Hasbro",
		"HCI+Group",
		"HealthStream",
		"Helen+of+Troy+Limited",
		"Heritage+Insurance",
		"HomeFed",
		"Hooker+Furniture",
		"Horizon+Global",
		"Hortonworks",
		"Hovnanian+Enterprises",
		"HRG+Group",
		"HubSpot",
		"IAC/InterActive",
		"Iconix+Brand+Group",
		"Imperva",
		"Independence+Holding",
		"Infinity+Property+and+Casualty",
		"Inovalon+Holdings",
		"Insight+Enterprises",
		"Instructure",
		"Internap",
		"IBM",
		"Interxion+Holding+N.V.",
		"Intuit",
		"iRobot",
		"j2+Global",
		"Jack+Henry+&+Associates",
		"James+River",
		"Jive+Software",
		"Johnson+Outdoors",
		"Kansas+City+Life+Insurance+Company",
		"Kate+Spade",
		"KB+Home",
		"LaZBoy",
		"Leaf+Group",
		"Leggett+&+Platt",
		"Leidos+Holdings",
		"Lennar",
		"LGI+Homes",
		"Libbey",
		"Lifetime+Brands",
		"Limelight+Networks",
		"Lincoln+National",
		"LivePerson",
		"LKQ+Corporation",
		"Loews+Corporation",
		"LogMeIn",
		"Luxoft+Holding",
		"M.D.C.+Holdings",
		"M/I+Homes",
		"Maiden+Holdings",
		"Malibu+Boats+Inc",
		"Manhattan+Associates",
		"Marine+Products",
		"Match+Group",
		"Mattel",
		"Matthews+International",
		"MCBC+Holdings",
		"Medidata+Solutions",
		"Meet+Group+Inc",
		"Mercury+General",
		"Meritage+Homes",
		"MetLife",
		"Microsoft",
		"MicroStrategy+Incorporated",
		"Mimecast",
		"MINDBODY",
		"Mitek+Systems",
		"MobileIron",
		"Model+N",
		"Mohawk+Industries",
		"Monotype+Imaging",
		"Motorcar+Parts+of+America",
		"Movado+Group",
		"Moxian",
		"MSA+Safety",
		"MuleSoft",
		"NACCO+Industries",
		"NantHealth",
		"National+General",
		"National+Instruments",
		"National+Presto",
		"National+Western+Life+Group",
		"Nautilus+Inc",
		"Navigators+Group",
		"NetScout+Systems",
		"NeuStar",
		"New+Home+Co.",
		"New+Relic",
		"Newell+Brands",
		"NIC+Inc",
		"NIKE",
		"NMI+Holdings",
		"Nuance+Communications",
		"Nutanix",
		"NVE+Corporation",
		"NVR",
		"Okta",
		"Old+Republic",
		"Ominto",
		"Omnicell",
		"OneBeacon+Insurance",
		"Oracle+Corporation",
		"Oxford+Industries",
		"Pandora+Media",
		"Park+City+Group",
		"Paychex",
		"Paycom",
		"Paylocity",
		"PayPal",
		"PC+Connection",
		"Pegasystems",
		"Perry+Ellis",
		"Polaris",
		"Presidio",
		"Primerica",
		"Progress+Software",
		"Progressive",
		"Proofpoint",
		"PROS+Holdings",
		"PTC+Inc.",
		"PulteGroup",
		"PVH",
		"Q2+Holdings",
		"Quality+Systems",
		"Qualys",
		"Rapid7",
		"RealNetworks",
		"RealPage",
		"Red+Hat",
		"Reinsurance+Group+of+America",
		"RenaissanceRe",
		"REV+Group",
		"Rightside+Group+Ltd",
		"RingCentral",
		"RLI+Corp.",
		"Rocket+Fuel",
		"Rubicon+Project",
		"Sabre",
		"Safety+Insurance+Group",
		"salesforce",
		"Science+Applications+International",
		"Scientific+Games+Corp",
		"Select+Comfort",
		"Selective+Insurance",
		"Sequential+Brands",
		"ServiceNow",
		"ServiceSource",
		"Shutterfly",
		"Shutterstock",
		"Silver+Spring+Networks",
		"Simulations+Plus",
		"Skechers",
		"Snap",
		"Snap-on",
		"Splunk",
		"SPS+Commerce",
		"Square",
		"SS&C+Technologies",
		"Stamps.com",
		"Standard+Motor+Products",
		"Stanley+Black+&+Decker",
		"State+Auto+Financial",
		"State+National",
		"Steven+Madden",
		"Sturm",
		"Superior+Uniform",
		"Sykes+Enterprises",
		"Symantec",
		"Synchronoss+Technologies",
		"Syntel",
		"Tableau",
		"Tabula+Rasa+Healthcare",
		"Take-Two+Interactive+Software",
		"Tangoe",
		"Taylor+Morrison+Home",
		"TechTarget",
		"Tempur+Sealy",
		"Teradata+Corporation",
		"Tesla",
		"Third+Point+Reinsurance",
		"Thor+Industries",
		"TiVo",
		"Toll+Brothers",
		"Torchmark",
		"Total+System+Services",
		"Travelers",
		"TRI+Pointe",
		"TriNet+Group",
		"TrueCar",
		"Tupperware+Brands",
		"Twilio",
		"Twitter",
		"Tyler+Technologies",
		"Ultimate+Software",
		"Under+Armour",
		"Unisys+Corporation",
		"United+Fire+Group",
		"United+Insurance+Holdings",
		"Universal+Electronics",
		"Universal+Insurance",
		"Unum+Group",
		"Upland+Software",
		"V.F.+Corporation",
		"Validus+Holdings",
		"Vantiv",
		"Varonis+Systems",
		"VASCO+Data+Security",
		"Veeva+Systems",
		"Vera+Bradley",
		"VeriFone",
		"Verint",
		"VeriSign",
		"VirnetX",
		"Virtusa",
		"Vista+Outdoor",
		"VMware",
		"Voya+Financial",
		"W.+R.+Berkley",
		"WageWorks",
		"Web.com",
		"WebMD",
		"Western+Union",
		"WEX",
		"Whirlpool",
		"White+Mountains+Insurance",
		"William+Lyon+Homes",
		"Winnebago",
		"Wolverine+World+Wide",
		"Workday",
		"Workiva",
		"Xactly",
		"Yahoo",
		"Yelp",
		"Yext",
		"Zendesk",
		"Zix",
		"Zynga",
		]
		search_url = [('https://www.google.com/trends/correlate/search?e=' + x + '&t=weekly&p=us') for x in search_list]
		for url in search_url:
			yield scrapy.Request(url, callback=self.parse_cor)

	def parse_cor(self, response):
		item = GcorItem()
		item['assoc_search'] = response.xpath('//div[@class="left results"]/h2/strong/text()').extract()[0]
		#Scraping initial search term to note as the mother search that all search terms are correlated to.
		search_terms = response.xpath('//li[@class="result selected"]/span/text()').extract()
		#Scraping name of selected highest correlated search term to assoc_search.
		search_terms.extend(response.xpath('//li[@class="result"]/a/text()').extract())
		#Scraping and concating remaining correlated search terms to assoc_search.
		corr_search_url = [('https://www.google.com/trends/correlate/search?e=' + x  +'&t=weekly&p=us') for x in search_terms][0:14]
		#Creating list of correlated search terms to scrape for their search activity time series. Only scraping top 15 to lighten
		#load due to Google's well-armed ability to halt scraping after heavy activity.

		## Creating first item before entering the for loop for assoc_search as the search_term itself.
		## Scrapy seems to want to ignore a request to return to a page that it's scraped before through scrapy.Request.

		item['search_term'] = response.xpath('//div[@class="left results"]/h2/strong/text()').extract()[0]
		#Scraping search term, whcih is the assoc_search term itself.
		exec('hist_search_activity = ' + response.xpath('/html/head/script[8]/text()').extract()[0].replace(']','[').split('[')[2])
		#Scraping data set of search activity time series nested in html head for javascript graph generation.
		corr_terms = response.xpath('//li[@class="result selected"]/span/text()').extract()
		#Scraping name of selected highest correlated search term to search_term.
		corr_terms.extend(response.xpath('//li[@class="result"]/a/text()').extract())
		#Scraping full set of correlated search terms to search_term.
		corr_terms_cor = response.xpath('//li[@class="result selected"]/small/text()').extract()
		#Scraping correlation of highest correlated search term to search_term.
		corr_terms_cor.extend(response.xpath('//li[@class="result"]/small/text()').extract())
		#Scraping correlations of full set of correlated search terms to search_term.
		item['hist_search_activity'] = hist_search_activity
		item['corr_terms'] = corr_terms[0:14]
		#Only scraping the top 15 for consistency to what will truly be scraped branching from the assoc_search.
		item['corr_terms_cor'] = [x for x in corr_terms_cor][0:14]
		yield item

		##Prepare item template to pass into the for loop for the correlated search terms.

		item = GcorItem()
		item['assoc_search'] = response.xpath('//div[@class="left results"]/h2/strong/text()').extract()[0]
		## Scraping initial search term and noting it for later meta reference.
		for url in corr_search_url:
			yield scrapy.Request(url, callback=self.parse_cor_all, meta={'item':item})
		## Pass the item as meta to ensure 'assoc search' is passed for the subsequent item yield-ing inside parse_cor_all.

	def parse_cor_all(self, response):
		item = response.meta['item']
		item['search_term'] = response.xpath('//div[@class="left results"]/h2/strong/text()').extract()[0]
		# >>>>>>>>> Why do we need exec here? <<<<<<<<<<<<<
		#Scraping search term, whcih is the assoc_search term itself.
		exec('hist_search_activity = ' + response.xpath('/html/head/script[8]/text()').extract()[0].replace(']','[').split('[')[2])
		#Scraping data set of search activity time series nested in html head for javascript graph generation.
		corr_terms = response.xpath('//li[@class="result selected"]/span/text()').extract()
		#Scraping name of selected highest correlated search term to search_term.
		corr_terms.extend(response.xpath('//li[@class="result"]/a/text()').extract())
		#Scraping full set of correlated search terms to search_term.
		corr_terms_cor = response.xpath('//li[@class="result selected"]/small/text()').extract()
		#Scraping correlation of highest correlated search term to search_term.
		corr_terms_cor.extend(response.xpath('//li[@class="result"]/small/text()').extract())
		#Scraping correlations of full set of correlated search terms to search_term.
		item['hist_search_activity'] = hist_search_activity
		item['corr_terms'] = corr_terms[0:14]
		#Only scraping the top 15 for consistency to what will truly be scraped branching from the assoc_search.
		item['corr_terms_cor'] = [x for x in corr_terms_cor][0:14]
		yield item


### S&P Small Cap Index (Future company data set selection for subsequnt project expansion)
# "8x8",
# "A+Schulman",
# "AAON",
# "AAR+CORP",
# "Abaxis",
# "Abercrombie+&",
# "ABM+Industries",
# "Acadia+Realty",
# "Aceto+Corporation",
# "Acorda+Therapeutics",
# "Actuant+Corporation",
# "ADTRAN",
# "Advanced+Energy",
# "AdvanSix",
# "Aegion+Corporation",
# "Aerojet+Rocketdyne",
# "AeroVironment",
# "Agilysys",
# "Agree+Realty",
# "AK+Steel",
# "Alamo+Group",
# "Albany+International",
# "Albany+Molecular",
# "Allegiant+Travel",
# "ALLETE",
# "Almost+Family",
# "AMAG+Pharmaceuticals",
# "Amedisys",
# "American+Assets",
# "American+Axle",
# "American+Equity",
# "American+Public+Education",
# "American+States+Water+Company",
# "American+Vanguard",
# "American+Woodmark",
# "Ameris+Bancorp",
# "AMERISAFE",
# "AMN+Healthcare",
# "Amphastar+Pharmaceuticals",
# "Analogic+Corporation",
# "Andersons",
# "AngioDynamics",
# "ANI+Pharmaceuticals",
# "Anika+Therapeutics",
# "Anixter+International",
# "Apogee+Enterprises",
# "Apollo+Commercial+Real+Estate",
# "Applied+Industrial+Technologies",
# "Applied+Optoelectronics",
# "ArcBest+Corporation",
# "Archrock+Inc",
# "Asbury+Automotive",
# "Ascena+Retail",
# "Astec+Industries",
# "Astoria+Financial",
# "Atlas+Air",
# "ATN+International",
# "Atwood+Oceanics",
# "Avista+Corporation",
# "Axon+Enterprise",
# "AZZ+Inc",
# "B&G+Foods",
# "Badger+Meter",
# "Balchem+Corporation",
# "Banc+of+California",
# "Bank+Mutual",
# "Banner+Corporation",
# "Barnes+&+Noble+Education",
# "Barnes+&+Noble",
# "Barnes+Group",
# "Bel+Fuse",
# "Belmond+Ltd",
# "Benchmark+Electronics",
# "Big+5+Sporting+Goods",
# "Biglari+Holdings",
# "Bill+Barrett",
# "BioTelemetry",
# "BJ's+Restaurants",
# "Black+Box",
# "Blackbaud",
# "Blucora",
# "Bob+Evans",
# "BofI+Holding",
# "Boise+Cascade",
# "Boston+Private+Financial+Holdings",
# "Bottomline+Technologies",
# "Boyd+Gaming",
# "Brady+Corporation",
# "Briggs+&+Stratton",
# "Brink's+Company",
# "Bristow+Group",
# "Brookline+Bancorp",
# "Brooks+Automation",
# "Buckle",
# "Cabot+Microelectronics",
# "CACI+International",
# "Cal-Maine+Foods",
# "CalAmp+Corp",
# "Calavo+Growers",
# "Caleres",
# "Calgon+Carbon",
# "California+Water+Service",
# "Callaway+Golf",
# "Cambrex+Corporation",
# "Cantel+Medical",
# "Capella+Education",
# "Capstead+Mortgage",
# "CARBO+Ceramics",
# "Cardtronics+plc",
# "Career+Education",
# "CareTrust+REIT",
# "Carrizo+Oil",
# "Cato+Corporation",
# "Cavco+Industries",
# "CBL+&+Associates",
# "CDI+Corp",
# "Cedar+Realty",
# "Celadon+Group",
# "Central+Garden",
# "Central+Garden",
# "Central+Pacific+Financial",
# "Century+Aluminum",
# "CEVA",
# "Chart+Industries",
# "Chemed+Corporation",
# "Chesapeake+Lodging",
# "Children's+Place",
# "Chuy's+Holdings",
# "Cincinnati+Bell",
# "CIRCOR+International",
# "City+Holding+Company",
# "Clearwater+Paper",
# "Cloud+Peak+Energy",
# "Coca-Cola+Bottling",
# "Cogent+Communications",
# "Cohu",
# "Columbia+Banking",
# "Comfort+Systems",
# "Community+Bank+System",
# "Community+Health+Systems",
# "Computer+Programs+and+Systems",
# "Comtech+Telecommunications",
# "CONMED+Corporation",
# "Consolidated+Communications",
# "Contango+Oil",
# "Cooper-Standard+Holdings",
# "Core-Mark+Holding",
# "CoreSite+Realty",
# "CorVel+Corporation",
# "Cray+Inc",
# "Crocs",
# "Cross+Country",
# "CryoLife",
# "CSG+Systems",
# "CTS+Corporation",
# "Cubic+Corporation",
# "Customers+Bancorp",
# "CVB+Financial",
# "Cytokinetics",
# "Daktronics",
# "Darling+Ingredients",
# "Dave+&+Buster's+Entertainment",
# "Deltic+Timber",
# "Denbury+Resources",
# "Depomed",
# "DHI+Group",
# "DiamondRock+Hospitality",
# "Digi+International",
# "Dime+Community",
# "DineEquity",
# "Diodes+Incorporated",
# "Diplomat+Pharmacy",
# "Donnelley+Financial",
# "Dorman+Products",
# "DSP+Group",
# "DSW+Inc",
# "DXP+Enterprises",
# "E",
# "Eagle+Pharmaceuticals",
# "EastGroup+Properties",
# "Ebix",
# "Echo+Global",
# "eHealth",
# "El+Paso",
# "El+Pollo",
# "Electro+Scientific",
# "Electronics+For",
# "Emergent+BioSolutions",
# "Employers+Holdings",
# "Enanta+Pharmaceuticals",
# "Encore+Capital",
# "Encore+Wire",
# "Engility+Holdings",
# "Enova+International",
# "EnPro+Industries",
# "Ensign+Group",
# "ePlus+inc",
# "Era+Group",
# "ESCO+Technologies",
# "Essendant+Inc",
# "Ethan+Allen",
# "Evercore+Partners",
# "Exar+Corporation",
# "ExlService+Holdings",
# "Exponent",
# "Express",
# "Exterran+Corp",
# "EZCORP",
# "Fabrinet+",
# "FARO+Technologies",
# "Federal+Signal",
# "Fidelity+Southern",
# "Fiesta+Restaurant",
# "Financial+Engines",
# "Finish+Line",
# "First+Bancorp",
# "First+Commonwealth",
# "First+Financial",
# "First+Financial",
# "First+Midwest",
# "FirstCash",
# "Five+Below",
# "Flotek+Industries",
# "Forestar+Group",
# "Forrester+Research",
# "Forward+Air",
# "Fossil+Group",
# "Four+Corners+Property+Trust",
# "Fox+Factory",
# "Francesca's+Holdings",
# "Franklin+Electric",
# "Franklin+Street",
# "Fred's",
# "FTD+Companies",
# "FutureFuel+Corp",
# "G-III+Apparel",
# "Gannett+Co",
# "General+Cable",
# "General+Communication",
# "Genesco+Inc",
# "Gentherm+Incorporated",
# "Geospace+Technologies",
# "Getty+Realty",
# "Gibraltar+Industries",
# "Gigamon+Inc",
# "Glacier+Bancorp",
# "Government+Properties",
# "Great+Western",
# "Green+Dot",
# "Green+Plains",
# "Greenbrier+Companies",
# "Greenhill+&",
# "Griffon+Corporation",
# "Group+1+Automotive",
# "Guess?",
# "Gulf+Island+Fabrication",
# "HB+Fuller",
# "Haemonetics+Corporation",
# "Hanmi+Financial",
# "Harmonic+Inc",
# "Harsco+Corporation",
# "Haverty+Furniture",
# "Hawaiian+Holdings",
# "Hawkins",
# "Haynes+International",
# "HCI+Group",
# "Headwaters+Incorporated",
# "Healthcare+Services",
# "HealthEquity+Inc",
# "HealthStream",
# "Heartland+Express",
# "Heidrick+&+Struggles",
# "Helix+Energy",
# "Hersha+Hospitality",
# "Heska+Corporation",
# "HFF",
# "Hibbett+Sports",
# "Hillenbrand",
# "HMS+Holdings",
# "Home+BancShares",
# "HomeStreet",
# "Hope+Bancorp",
# "Horace+Mann+Educators",
# "Hornbeck+Offshore",
# "Hub+Group",
# "Iconix+Brand",
# "ICU+Medical",
# "II-VI+Incorporated",
# "ILG",
# "Impax+Laboratories",
# "Independent+Bank",
# "Infinity+Property",
# "Ingevity+Corporation",
# "Innophos+Holdings",
# "Innospec+Inc",
# "Innoviva",
# "Inogen",
# "Insight+Enterprises",
# "Insperity",
# "Installed+Building+Products",
# "Insteel+Industries",
# "Integer+Holdings",
# "Integra+LifeSciences",
# "Inter+Parfums",
# "Interactive+Brokers",
# "Interface",
# "INTL+FCStone",
# "Invacare+Corporation",
# "Investment+Technology",
# "Iridium+Communications",
# "iRobot+Corporation",
# "Itron",
# "J&J+Snack+Foods",
# "John+B+Sanfilippo+&+Son",
# "John+Bean+Technologies",
# "Kaiser+Aluminum",
# "Kaman+Corporation",
# "KapStone+Paper",
# "Kelly+Services",
# "Kindred+Healthcare",
# "Kirkland's",
# "Kite+Realty",
# "Knight+Transportation",
# "Kopin+Corporation",
# "Koppers+Holdings",
# "Korn/Ferry+International",
# "Kraton+Corporation",
# "Kulicke+&",
# "Landauer",
# "Lannett+Company",
# "LaZBoy+Incorporated",
# "LCI+Industries",
# "LegacyTexas+Financial",
# "LeMaitre+Vascular",
# "LendingTree",
# "Lexington+Realty",
# "LGI+Homes",
# "LHC+Group",
# "Ligand+Pharmaceuticals",
# "Lindsay+Corporation",
# "Liquidity+Services",
# "Lithia+Motors",
# "LivePerson",
# "LSB+Industries",
# "LSC+Communications",
# "LTC+Properties",
# "Lumber+Liquidators",
# "Lumentum+Holdings",
# "Luminex+Corp",
# "Lumos+Networks",
# "Lydall",
# "MC+Holdings",
# "M/I+Homes",
# "Magellan+Health",
# "Maiden+Holdings",
# "ManTech+International",
# "Marcus+Corporation",
# "MarineMax",
# "Marriott+Vacations",
# "Marten+Transport",
# "Materion+Corporation",
# "Matrix+Service",
# "Matson",
# "Matthews+International",
# "Medicines+Company",
# "Medidata+Solutions",
# "Medifast",
# "Mercury+Systems",
# "Meridian+Bioscience",
# "Merit+Medical",
# "Meritage+Homes",
# "Methode+Electronics",
# "MicroStrategy+Incorporated",
# "MiMedx+Group",
# "MKS+Instruments",
# "Mobile+Mini",
# "Momenta+Pharmaceuticals",
# "Monarch+Casino",
# "Monotype+Imaging",
# "Monro+Muffler",
# "Moog+Inc",
# "Motorcar+Parts",
# "Movado+Group",
# "MTS+Systems",
# "Mueller+Industries",
# "Multi-Color+Corporation",
# "Myers+Industries",
# "MYR+Group",
# "Myriad+Genetics",
# "Nanometrics+Incorporated",
# "National+Bank",
# "National+Presto",
# "Natus+Medical",
# "Nautilus+Inc",
# "Navigant+Consulting",
# "Navigators+Group",
# "NBT+Bancorp",
# "Neenah+Paper",
# "Nektar+Therapeutics",
# "Neogen+Corporation",
# "NETGEAR",
# "New+Media+Investment+Group",
# "Newpark+Resources",
# "NIC+Inc",
# "Northern+Oil",
# "Northfield+Bancorp",
# "Northwest+Bancshares",
# "Northwest+Natural",
# "Nutrisystem",
# "Oclaro",
# "OFG+Bancorp",
# "Old+National",
# "Ollie's+Bargain",
# "Olympic+Steel",
# "Omnicell",
# "On+Assignment",
# "Opus+Bank",
# "OraSure+Technologies",
# "Orion+Group",
# "Oritani+Financial",
# "Orthofix+International",
# "OSI+Systems",
# "Oxford+Industries",
# "P+H+Glatfelter",
# "Park+Electrochemical",
# "Parkway",
# "Patrick+Industries",
# "PDC+Energy",
# "Penn+National",
# "Pennsylvania+Real",
# "Perficient",
# "Perry+Ellis",
# "PetMed+Express",
# "PGT+Innovations",
# "PharMerica+Corporation",
# "Phibro+Animal",
# "Pinnacle+Financial",
# "Pioneer+Energy",
# "Piper+Jaffray",
# "Plexus+Corp",
# "Powell+Industries",
# "Power+Integrations",
# "PRA+Group",
# "ProAssurance+Corporation",
# "Progenics+Pharmaceuticals",
# "Progress+Software",
# "Proto+Labs",
# "Providence+Service",
# "Provident+Financial",
# "PS+Business+Parks",
# "Quaker+Chemical",
# "Quality+Systems",
# "Qualys",
# "Quanex+Building",
# "QuinStreet",
# "Quorum+Health",
# "RR+Donnelley",
# "Rambus+Inc",
# "Raven+Industries",
# "Rayonier+Advanced+Materials",
# "RE/MAX+Holdings",
# "Red+Robin",
# "Regis+Corporation",
# "Rent-A-Center+Inc",
# "Repligen+Corporation",
# "Resources+Connection",
# "Retail+Opportunity+Investment",
# "REX+American",
# "RH+",
# "RLI+Corp",
# "Roadrunner+Transportation",
# "Rogers+Corporation",
# "Ruby+Tuesday",
# "Rudolph+Technologies",
# "Ruth's+Hospitality",
# "S&T+Bancorp",
# "Sabra+Health",
# "Safety+Insurance",
# "Saia",
# "Sanderson+Farms",
# "Sanmina-SCI+Corporation",
# "Saul+Centers",
# "ScanSource",
# "Scholastic+Corporation",
# "Schweitzer-Mauduit+International",
# "SciClone+Pharmaceuticals",
# "Scientific+Games",
# "SEACOR+Holdings",
# "Select+Comfort",
# "Select+Medical",
# "Selective+Insurance",
# "Semtech+Corporation",
# "Seneca+Foods",
# "ServisFirst+Bancshares",
# "Shake+Shack",
# "Shoe+Carnival",
# "Shutterfly",
# "Shutterstock",
# "Simmons+First",
# "Simpson+Manufacturing",
# "SkyWest",
# "Sonic+Automotive",
# "Sonic+Corp",
# "South+Jersey",
# "Southside+Bancshares",
# "SpartanNash+Company",
# "Spectrum+Pharmaceuticals",
# "Spire+Inc",
# "Spok+Holdings",
# "SPS+Commerce",
# "SPX+Corporation",
# "SPX+Flow",
# "SRC+Energy",
# "Stamps",
# "Standard+Motor",
# "Standex+International",
# "Stein+Mart",
# "Stepan+Company",
# "Sterling+Bancorp",
# "Steven+Madden",
# "Stewart+Information",
# "Strayer+Education",
# "Sturm",
# "Sucampo+Pharmaceuticals",
# "Summit+Hotel+Properties",
# "SunCoke+Energy",
# "Super+Micro",
# "Superior+Industries",
# "Supernus+Pharmaceuticals",
# "SUPERVALU+INC",
# "Surmodics+Inc",
# "Sykes+Enterprises",
# "Synchronoss+Technologies",
# "Tailored+Brands",
# "Team",
# "TeleTech+Holdings",
# "Tennant+Company",
# "Tesco+Corporation",
# "Tetra+Tech",
# "TETRA+Technologies",
# "Tidewater+Inc",
# "Tile+Shop",
# "TimkenSteel+Corp",
# "Titan+International",
# "Tivity+Health",
# "TiVo+Corp",
# "Tompkins+Financial",
# "TopBuild+Corp",
# "Tredegar+Corporation",
# "Trex+Company",
# "Triumph+Group",
# "TrueBlue",
# "TrustCo+Bank",
# "TTM+Technologies",
# "Tuesday+Morning",
# "US+Concrete",
# "US+Physical+Therapy",
# "US+Silica",
# "Ultratech",
# "Unifi",
# "UniFirst+Corporation",
# "Unit+Corporation",
# "United+Community",
# "United+Fire",
# "United+Insurance",
# "Universal+Corp",
# "Universal+Electronics",
# "Universal+Forest",
# "Universal+Health",
# "Universal+Insurance",
# "Urstadt+Biddle",
# "US+Ecology",
# "Varex+Imaging",
# "VASCO+Data",
# "Veeco+Instruments",
# "Vera+Bradley",
# "Veritiv+Corp",
# "Viad+Corp",
# "Viavi+Solutions",
# "Vicor+Corporation",
# "Virtus+Investment",
# "Virtusa+Corporation",
# "Vista+Outdoor",
# "Vitamin+Shoppe",
# "Wabash+National",
# "Waddell+&+Reed+Financial",
# "WageWorks",
# "Walker+&",
# "Watts+Water",
# "WD-40+Company",
# "Westamerica+Bancorporation",
# "William+Lyon",
# "Wingstop",
# "Winnebago+Industries",
# "WisdomTree+Investments",
# "Wolverine+World",
# "World+Acceptance",
# "World+Wrestling",
# "XO+Group",
# "Xperi+Corp",
# "Zumiez+Inc",
