# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRatings',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=50)),
                ('ratingDate', models.DateField(default='', max_length=20)),
                ('rating', models.CharField(default='', max_length=20)),
                ('ratingClass', models.CharField(default='', max_length=20)),
                ('brokerageFirm', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
